//------------------------------------------------------------------------------
//     This code was generated by Morphis Forms2Net  tool.
//     Forms2Net Version: 1.4.11.0
//	   Generation Date: 01/06/2020
//------------------------------------------------------------------------------




using System;

namespace Alio.Forms.Fjpst01a.Model {
	
	///F2N_INFO
	/// This file contains the definition of all the exceptions that were declared in the PLSQL code
	/// of module FJPST01A. Each exception is defined as class derived from
	/// System.Exception class.
	///
	
	
	public class ETooManyParms: System.Exception {}

	public class Unhandled: System.Exception {}

}
