//------------------------------------------------------------------------------
//     This code was generated by Morphis Forms2Net  tool.
//     Forms2Net Version: 1.4.11.0
//	   Generation Date: 01/06/2020
//------------------------------------------------------------------------------




using System;

namespace Alio.Forms.Fjent03a.Types {
	
	///F2N_INFO
	/// This file contains the definition of all unknown types referenced in the PLSQL code
	/// of module FJENT03A. 
	///
	
	
	public class Formmodule{}

	public class ReportObject{}

	public class OraJavaJobject{}

	public class WebutilFileFileList{}

	public class Parameterhandle{}

	public class Parameterlist{}

	public class Pointer{}

	public class Functionhandle{}

	public class JniArglist{}

	public class OraFfiLibhandletype{}

	public class ListType{}

	public class ObjType{}

	public class Fsact07aAccountTable{}

	public class Fsact07aAccountRecord{}

}
