//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alio.Forms.Fjent01a.Views.locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alio.Forms.Fjent01a.Views.locales.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string accountAlert_btn1_label {
            get {
                return ResourceManager.GetString("accountAlert_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string accountAlert_btn2_label {
            get {
                return ResourceManager.GetString("accountAlert_btn2_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Chain.
        /// </summary>
        internal static string approvalChains_approvalChain_title {
            get {
                return ResourceManager.GetString("approvalChains_approvalChain_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Chains.
        /// </summary>
        internal static string approvalChains_title {
            get {
                return ResourceManager.GetString("approvalChains_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : BATCH_DATE.
        /// </summary>
        internal static string batchNoBlock_batchDate_hint {
            get {
                return ResourceManager.GetString("batchNoBlock_batchDate_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Date.
        /// </summary>
        internal static string batchNoBlock_batchDate_label {
            get {
                return ResourceManager.GetString("batchNoBlock_batchDate_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : BATCH_NO.
        /// </summary>
        internal static string batchNoBlock_batchNo_hint {
            get {
                return ResourceManager.GetString("batchNoBlock_batchNo_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch No.
        /// </summary>
        internal static string batchNoBlock_batchNo_label {
            get {
                return ResourceManager.GetString("batchNoBlock_batchNo_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date List of Values.
        /// </summary>
        internal static string dateLovWindow_title {
            get {
                return ResourceManager.GetString("dateLovWindow_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Save As Is.
        /// </summary>
        internal static string debitCredit_btn1_label {
            get {
                return ResourceManager.GetString("debitCredit_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, Edit Entries.
        /// </summary>
        internal static string debitCredit_btn2_label {
            get {
                return ResourceManager.GetString("debitCredit_btn2_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit and Credit Totals do not match! 
        ///(Out of balance journal entries will not post) 
        ///Do you want to save anyway? .
        /// </summary>
        internal static string debitCredit_text {
            get {
                return ResourceManager.GetString("debitCredit_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Balance.
        /// </summary>
        internal static string debitCredit_title {
            get {
                return ResourceManager.GetString("debitCredit_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : JOURNAL_AMOUNT.
        /// </summary>
        internal static string jeData_accountBalance_hint {
            get {
                return ResourceManager.GetString("jeData_accountBalance_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Amount.
        /// </summary>
        internal static string jeData_accountBalance_label {
            get {
                return ResourceManager.GetString("jeData_accountBalance_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Balance.
        /// </summary>
        internal static string jeData_accountBalance_prompttext {
            get {
                return ResourceManager.GetString("jeData_accountBalance_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Description.
        /// </summary>
        internal static string jeData_accountDesc_prompttext {
            get {
                return ResourceManager.GetString("jeData_accountDesc_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : ACCOUNT_ID.
        /// </summary>
        internal static string jeData_accountId_hint {
            get {
                return ResourceManager.GetString("jeData_accountId_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account ID.
        /// </summary>
        internal static string jeData_accountId_label {
            get {
                return ResourceManager.GetString("jeData_accountId_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : ACCOUNT_NO.
        /// </summary>
        internal static string jeData_accountNo_hint {
            get {
                return ResourceManager.GetString("jeData_accountNo_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No.
        /// </summary>
        internal static string jeData_accountNo_label {
            get {
                return ResourceManager.GetString("jeData_accountNo_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No.
        /// </summary>
        internal static string jeData_accountNo_prompttext {
            get {
                return ResourceManager.GetString("jeData_accountNo_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : JOURNAL_AMOUNT.
        /// </summary>
        internal static string jeData_crAmount_hint {
            get {
                return ResourceManager.GetString("jeData_crAmount_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Amount.
        /// </summary>
        internal static string jeData_crAmount_label {
            get {
                return ResourceManager.GetString("jeData_crAmount_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Amount.
        /// </summary>
        internal static string jeData_crAmount_prompttext {
            get {
                return ResourceManager.GetString("jeData_crAmount_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : DEBIT_CREDIT_FLAG.
        /// </summary>
        internal static string jeData_debitCreditFlag_hint {
            get {
                return ResourceManager.GetString("jeData_debitCreditFlag_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Credit Flag.
        /// </summary>
        internal static string jeData_debitCreditFlag_label {
            get {
                return ResourceManager.GetString("jeData_debitCreditFlag_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : JOURNAL_AMOUNT.
        /// </summary>
        internal static string jeData_drAmount_hint {
            get {
                return ResourceManager.GetString("jeData_drAmount_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Amount.
        /// </summary>
        internal static string jeData_drAmount_label {
            get {
                return ResourceManager.GetString("jeData_drAmount_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Amount.
        /// </summary>
        internal static string jeData_drAmount_prompttext {
            get {
                return ResourceManager.GetString("jeData_drAmount_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string jeData_drTotal_prompttext {
            get {
                return ResourceManager.GetString("jeData_drTotal_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : ACCOUNT_ID.
        /// </summary>
        internal static string jeData_holdAccountId_hint {
            get {
                return ResourceManager.GetString("jeData_holdAccountId_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account ID.
        /// </summary>
        internal static string jeData_holdAccountId_label {
            get {
                return ResourceManager.GetString("jeData_holdAccountId_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : JOURNAL_AMOUNT.
        /// </summary>
        internal static string jeData_holdCrAmount_hint {
            get {
                return ResourceManager.GetString("jeData_holdCrAmount_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Amount.
        /// </summary>
        internal static string jeData_holdCrAmount_label {
            get {
                return ResourceManager.GetString("jeData_holdCrAmount_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Amount.
        /// </summary>
        internal static string jeData_holdCrAmount_prompttext {
            get {
                return ResourceManager.GetString("jeData_holdCrAmount_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : JOURNAL_AMOUNT.
        /// </summary>
        internal static string jeData_holdDrAmount_hint {
            get {
                return ResourceManager.GetString("jeData_holdDrAmount_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Amount.
        /// </summary>
        internal static string jeData_holdDrAmount_label {
            get {
                return ResourceManager.GetString("jeData_holdDrAmount_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Amount.
        /// </summary>
        internal static string jeData_holdDrAmount_prompttext {
            get {
                return ResourceManager.GetString("jeData_holdDrAmount_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : JOURNAL_AMOUNT.
        /// </summary>
        internal static string jeData_holdJournalAmount_hint {
            get {
                return ResourceManager.GetString("jeData_holdJournalAmount_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Amount.
        /// </summary>
        internal static string jeData_holdJournalAmount_label {
            get {
                return ResourceManager.GetString("jeData_holdJournalAmount_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : JOURNAL_AMOUNT.
        /// </summary>
        internal static string jeData_journalAmount_hint {
            get {
                return ResourceManager.GetString("jeData_journalAmount_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Amount.
        /// </summary>
        internal static string jeData_journalAmount_label {
            get {
                return ResourceManager.GetString("jeData_journalAmount_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : LINE_NO.
        /// </summary>
        internal static string jeData_lineNo_hint {
            get {
                return ResourceManager.GetString("jeData_lineNo_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line No.
        /// </summary>
        internal static string jeData_lineNo_label {
            get {
                return ResourceManager.GetString("jeData_lineNo_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : REFERENCE_NO.
        /// </summary>
        internal static string jeData_referenceNo_hint {
            get {
                return ResourceManager.GetString("jeData_referenceNo_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference No.
        /// </summary>
        internal static string jeData_referenceNo_label {
            get {
                return ResourceManager.GetString("jeData_referenceNo_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Chain.
        /// </summary>
        internal static string jeHeader_approvalChain_prompttext {
            get {
                return ResourceManager.GetString("jeHeader_approvalChain_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : JOURNAL_DESCRIPTION.
        /// </summary>
        internal static string jeHeader_approvalStatusDesc_hint {
            get {
                return ResourceManager.GetString("jeHeader_approvalStatusDesc_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Description.
        /// </summary>
        internal static string jeHeader_approvalStatusDesc_label {
            get {
                return ResourceManager.GetString("jeHeader_approvalStatusDesc_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string jeHeader_approvalStatusDesc_prompttext {
            get {
                return ResourceManager.GetString("jeHeader_approvalStatusDesc_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference .
        /// </summary>
        internal static string jeHeader_assignReference_label {
            get {
                return ResourceManager.GetString("jeHeader_assignReference_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : BATCH_NO.
        /// </summary>
        internal static string jeHeader_batchNo_hint {
            get {
                return ResourceManager.GetString("jeHeader_batchNo_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch No.
        /// </summary>
        internal static string jeHeader_batchNo_label {
            get {
                return ResourceManager.GetString("jeHeader_batchNo_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch No.
        /// </summary>
        internal static string jeHeader_batchNo_prompttext {
            get {
                return ResourceManager.GetString("jeHeader_batchNo_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Year.
        /// </summary>
        internal static string jeHeader_batchYear_prompttext {
            get {
                return ResourceManager.GetString("jeHeader_batchYear_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Total.
        /// </summary>
        internal static string jeHeader_creditTotal_prompttext {
            get {
                return ResourceManager.GetString("jeHeader_creditTotal_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Total.
        /// </summary>
        internal static string jeHeader_debitTotal_prompttext {
            get {
                return ResourceManager.GetString("jeHeader_debitTotal_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : JOURNAL_DATE.
        /// </summary>
        internal static string jeHeader_journalDate_hint {
            get {
                return ResourceManager.GetString("jeHeader_journalDate_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Date.
        /// </summary>
        internal static string jeHeader_journalDate_label {
            get {
                return ResourceManager.GetString("jeHeader_journalDate_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string jeHeader_journalDate_prompttext {
            get {
                return ResourceManager.GetString("jeHeader_journalDate_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-Click for Calendar.
        /// </summary>
        internal static string jeHeader_journalDate_tooltip {
            get {
                return ResourceManager.GetString("jeHeader_journalDate_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : JOURNAL_DESCRIPTION.
        /// </summary>
        internal static string jeHeader_journalDescription_hint {
            get {
                return ResourceManager.GetString("jeHeader_journalDescription_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Description.
        /// </summary>
        internal static string jeHeader_journalDescription_label {
            get {
                return ResourceManager.GetString("jeHeader_journalDescription_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string jeHeader_journalDescription_prompttext {
            get {
                return ResourceManager.GetString("jeHeader_journalDescription_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready for Approval.
        /// </summary>
        internal static string jeHeader_readyForApproval_label {
            get {
                return ResourceManager.GetString("jeHeader_readyForApproval_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : REFERENCE_NO.
        /// </summary>
        internal static string jeHeader_referenceNo_hint {
            get {
                return ResourceManager.GetString("jeHeader_referenceNo_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference No.
        /// </summary>
        internal static string jeHeader_referenceNo_label {
            get {
                return ResourceManager.GetString("jeHeader_referenceNo_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spreadsheet.
        /// </summary>
        internal static string jeHeader_spreasdsheet_label {
            get {
                return ResourceManager.GetString("jeHeader_spreasdsheet_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string jeHeader_viewButton_label {
            get {
                return ResourceManager.GetString("jeHeader_viewButton_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order No.
        /// </summary>
        internal static string jeHeader_whsOrderNo_prompttext {
            get {
                return ResourceManager.GetString("jeHeader_whsOrderNo_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Entry.
        /// </summary>
        internal static string journalEntry_title {
            get {
                return ResourceManager.GetString("journalEntry_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string noRecord_btn1_label {
            get {
                return ResourceManager.GetString("noRecord_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string noRecord_btn2_label {
            get {
                return ResourceManager.GetString("noRecord_btn2_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were no records found - Please choose a mode.
        /// </summary>
        internal static string noRecord_text {
            get {
                return ResourceManager.GetString("noRecord_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a mode.
        /// </summary>
        internal static string noRecord_title {
            get {
                return ResourceManager.GetString("noRecord_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string onErrorCaution_btn1_label {
            get {
                return ResourceManager.GetString("onErrorCaution_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string onErrorStop_btn1_label {
            get {
                return ResourceManager.GetString("onErrorStop_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string onMessage_btn1_label {
            get {
                return ResourceManager.GetString("onMessage_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string overBudgetNoOverride_btn1_label {
            get {
                return ResourceManager.GetString("overBudgetNoOverride_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string overBudgetNoOverride_btn2_label {
            get {
                return ResourceManager.GetString("overBudgetNoOverride_btn2_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string overBudgetOverride_btn1_label {
            get {
                return ResourceManager.GetString("overBudgetOverride_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string overBudgetOverride_btn2_label {
            get {
                return ResourceManager.GetString("overBudgetOverride_btn2_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Continue.
        /// </summary>
        internal static string spreadsheetAlert_btn1_label {
            get {
                return ResourceManager.GetString("spreadsheetAlert_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string spreadsheetAlert_btn2_label {
            get {
                return ResourceManager.GetString("spreadsheetAlert_btn2_label", resourceCulture);
            }
        }
    }
}
