//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alio.Forms.Fjgen01a.Views.locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alio.Forms.Fjgen01a.Views.locales.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string accountAlert_btn1_label {
            get {
                return ResourceManager.GetString("accountAlert_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string accountAlert_btn2_label {
            get {
                return ResourceManager.GetString("accountAlert_btn2_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journals Inquiry.
        /// </summary>
        internal static string journalInqury_title {
            get {
                return ResourceManager.GetString("journalInqury_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : ACCOUNT_DESC.
        /// </summary>
        internal static string journals_accountDesc_hint {
            get {
                return ResourceManager.GetString("journals_accountDesc_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Description.
        /// </summary>
        internal static string journals_accountDesc_label {
            get {
                return ResourceManager.GetString("journals_accountDesc_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : ACCOUNT_ID.
        /// </summary>
        internal static string journals_accountId_hint {
            get {
                return ResourceManager.GetString("journals_accountId_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account ID.
        /// </summary>
        internal static string journals_accountId_label {
            get {
                return ResourceManager.GetString("journals_accountId_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account ID.
        /// </summary>
        internal static string journals_accountId_prompttext {
            get {
                return ResourceManager.GetString("journals_accountId_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : ACCOUNT_NO.
        /// </summary>
        internal static string journals_accountNo_hint {
            get {
                return ResourceManager.GetString("journals_accountNo_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string journals_accountNo_label {
            get {
                return ResourceManager.GetString("journals_accountNo_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : ACCOUNT_PERIOD.
        /// </summary>
        internal static string journals_accountPeriod_hint {
            get {
                return ResourceManager.GetString("journals_accountPeriod_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Period.
        /// </summary>
        internal static string journals_accountPeriod_label {
            get {
                return ResourceManager.GetString("journals_accountPeriod_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string journals_accountPeriod_prompttext {
            get {
                return ResourceManager.GetString("journals_accountPeriod_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : ACCOUNT_TYPE.
        /// </summary>
        internal static string journals_accountType_hint {
            get {
                return ResourceManager.GetString("journals_accountType_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        internal static string journals_accountType_label {
            get {
                return ResourceManager.GetString("journals_accountType_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Year.
        /// </summary>
        internal static string journals_accountYear_label {
            get {
                return ResourceManager.GetString("journals_accountYear_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : BATCH_NO.
        /// </summary>
        internal static string journals_batchNo_hint {
            get {
                return ResourceManager.GetString("journals_batchNo_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch.
        /// </summary>
        internal static string journals_batchNo_label {
            get {
                return ResourceManager.GetString("journals_batchNo_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch.
        /// </summary>
        internal static string journals_batchNo_prompttext {
            get {
                return ResourceManager.GetString("journals_batchNo_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : BATCH_YEAR.
        /// </summary>
        internal static string journals_batchYear_hint {
            get {
                return ResourceManager.GetString("journals_batchYear_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string journals_batchYear_label {
            get {
                return ResourceManager.GetString("journals_batchYear_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : CHECK_KEY.
        /// </summary>
        internal static string journals_checkKey_hint {
            get {
                return ResourceManager.GetString("journals_checkKey_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Key.
        /// </summary>
        internal static string journals_checkKey_label {
            get {
                return ResourceManager.GetString("journals_checkKey_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        internal static string journals_checkKey_prompttext {
            get {
                return ResourceManager.GetString("journals_checkKey_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : CLAIM_NO.
        /// </summary>
        internal static string journals_claimNo_hint {
            get {
                return ResourceManager.GetString("journals_claimNo_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim.
        /// </summary>
        internal static string journals_claimNo_label {
            get {
                return ResourceManager.GetString("journals_claimNo_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim.
        /// </summary>
        internal static string journals_claimNo_prompttext {
            get {
                return ResourceManager.GetString("journals_claimNo_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : DEBIT_CREDIT_FLAG.
        /// </summary>
        internal static string journals_debitCreditFlag_hint {
            get {
                return ResourceManager.GetString("journals_debitCreditFlag_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Credit Flag.
        /// </summary>
        internal static string journals_debitCreditFlag_label {
            get {
                return ResourceManager.GetString("journals_debitCreditFlag_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        internal static string journals_debitCreditFlag_prompttext {
            get {
                return ResourceManager.GetString("journals_debitCreditFlag_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dup Rec.
        /// </summary>
        internal static string journals_dupRec_label {
            get {
                return ResourceManager.GetString("journals_dupRec_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : JOURNAL_AMOUNT.
        /// </summary>
        internal static string journals_journalAmount_hint {
            get {
                return ResourceManager.GetString("journals_journalAmount_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Amount.
        /// </summary>
        internal static string journals_journalAmount_label {
            get {
                return ResourceManager.GetString("journals_journalAmount_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string journals_journalAmount_prompttext {
            get {
                return ResourceManager.GetString("journals_journalAmount_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : JOURNAL_DATE.
        /// </summary>
        internal static string journals_journalDate_hint {
            get {
                return ResourceManager.GetString("journals_journalDate_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Date.
        /// </summary>
        internal static string journals_journalDate_label {
            get {
                return ResourceManager.GetString("journals_journalDate_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string journals_journalDate_prompttext {
            get {
                return ResourceManager.GetString("journals_journalDate_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : JOURNAL_DESCRIPTION.
        /// </summary>
        internal static string journals_journalDescription_hint {
            get {
                return ResourceManager.GetString("journals_journalDescription_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Description.
        /// </summary>
        internal static string journals_journalDescription_label {
            get {
                return ResourceManager.GetString("journals_journalDescription_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string journals_journalDescription_prompttext {
            get {
                return ResourceManager.GetString("journals_journalDescription_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : JOURNAL_ID.
        /// </summary>
        internal static string journals_journalId_hint {
            get {
                return ResourceManager.GetString("journals_journalId_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal ID.
        /// </summary>
        internal static string journals_journalId_label {
            get {
                return ResourceManager.GetString("journals_journalId_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal ID.
        /// </summary>
        internal static string journals_journalId_prompttext {
            get {
                return ResourceManager.GetString("journals_journalId_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : JOURNAL_SEQ_NO.
        /// </summary>
        internal static string journals_journalSeqNo_hint {
            get {
                return ResourceManager.GetString("journals_journalSeqNo_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Seq.
        /// </summary>
        internal static string journals_journalSeqNo_label {
            get {
                return ResourceManager.GetString("journals_journalSeqNo_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seq.
        /// </summary>
        internal static string journals_journalSeqNo_prompttext {
            get {
                return ResourceManager.GetString("journals_journalSeqNo_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : JOURNAL_TYPE.
        /// </summary>
        internal static string journals_journalType_hint {
            get {
                return ResourceManager.GetString("journals_journalType_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Type.
        /// </summary>
        internal static string journals_journalType_label {
            get {
                return ResourceManager.GetString("journals_journalType_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string journals_journalType_prompttext {
            get {
                return ResourceManager.GetString("journals_journalType_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : REFERENCE_NO.
        /// </summary>
        internal static string journals_referenceNo_hint {
            get {
                return ResourceManager.GetString("journals_referenceNo_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string journals_referenceNo_label {
            get {
                return ResourceManager.GetString("journals_referenceNo_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string journals_referenceNo_prompttext {
            get {
                return ResourceManager.GetString("journals_referenceNo_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : REFERENCE_SEQ_NO.
        /// </summary>
        internal static string journals_referenceSeqNo_hint {
            get {
                return ResourceManager.GetString("journals_referenceSeqNo_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Seq.
        /// </summary>
        internal static string journals_referenceSeqNo_label {
            get {
                return ResourceManager.GetString("journals_referenceSeqNo_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seq.
        /// </summary>
        internal static string journals_referenceSeqNo_prompttext {
            get {
                return ResourceManager.GetString("journals_referenceSeqNo_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : REFERENCE_TYPE.
        /// </summary>
        internal static string journals_referenceType_hint {
            get {
                return ResourceManager.GetString("journals_referenceType_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Type.
        /// </summary>
        internal static string journals_referenceType_label {
            get {
                return ResourceManager.GetString("journals_referenceType_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string noRecord_btn1_label {
            get {
                return ResourceManager.GetString("noRecord_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string noRecord_btn2_label {
            get {
                return ResourceManager.GetString("noRecord_btn2_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were no records found - Please choose a mode.
        /// </summary>
        internal static string noRecord_text {
            get {
                return ResourceManager.GetString("noRecord_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a mode.
        /// </summary>
        internal static string noRecord_title {
            get {
                return ResourceManager.GetString("noRecord_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string onErrorCaution_btn1_label {
            get {
                return ResourceManager.GetString("onErrorCaution_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string onErrorStop_btn1_label {
            get {
                return ResourceManager.GetString("onErrorStop_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string onMessage_btn1_label {
            get {
                return ResourceManager.GetString("onMessage_btn1_label", resourceCulture);
            }
        }
    }
}
