//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alio.Forms.Fjent03a.Views.locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alio.Forms.Fjent03a.Views.locales.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string accountAlert_btn1_label {
            get {
                return ResourceManager.GetString("accountAlert_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string accountAlert_btn2_label {
            get {
                return ResourceManager.GetString("accountAlert_btn2_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Chain.
        /// </summary>
        internal static string approvalChains_approvalChain_title {
            get {
                return ResourceManager.GetString("approvalChains_approvalChain_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Chains.
        /// </summary>
        internal static string approvalChains_title {
            get {
                return ResourceManager.GetString("approvalChains_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch No.
        /// </summary>
        internal static string batchNoBlock_accountingPeriod_label {
            get {
                return ResourceManager.GetString("batchNoBlock_accountingPeriod_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : BATCH_DATE.
        /// </summary>
        internal static string batchNoBlock_batchDate_hint {
            get {
                return ResourceManager.GetString("batchNoBlock_batchDate_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Date.
        /// </summary>
        internal static string batchNoBlock_batchDate_label {
            get {
                return ResourceManager.GetString("batchNoBlock_batchDate_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : BATCH_NO.
        /// </summary>
        internal static string batchNoBlock_batchNo_hint {
            get {
                return ResourceManager.GetString("batchNoBlock_batchNo_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch No.
        /// </summary>
        internal static string batchNoBlock_batchNo_label {
            get {
                return ResourceManager.GetString("batchNoBlock_batchNo_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch No.
        /// </summary>
        internal static string batchNoBlock_batchNo_prompttext {
            get {
                return ResourceManager.GetString("batchNoBlock_batchNo_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Year.
        /// </summary>
        internal static string batchNoBlock_batchYear_prompttext {
            get {
                return ResourceManager.GetString("batchNoBlock_batchYear_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Balance.
        /// </summary>
        internal static string batchNoBlock_showBal_label {
            get {
                return ResourceManager.GetString("batchNoBlock_showBal_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date List of Values.
        /// </summary>
        internal static string dateLovWindow_title {
            get {
                return ResourceManager.GetString("dateLovWindow_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Batch Desc.
        /// </summary>
        internal static string descButtons_descriptionType_batch_label {
            get {
                return ResourceManager.GetString("descButtons_descriptionType_batch_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use My Own Desc.
        /// </summary>
        internal static string descButtons_descriptionType_none_label {
            get {
                return ResourceManager.GetString("descButtons_descriptionType_none_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Desc.
        /// </summary>
        internal static string descButtons_descriptionType_repeat_label {
            get {
                return ResourceManager.GetString("descButtons_descriptionType_repeat_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string noRecord_btn1_label {
            get {
                return ResourceManager.GetString("noRecord_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string noRecord_btn2_label {
            get {
                return ResourceManager.GetString("noRecord_btn2_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were no records found - Please choose a mode.
        /// </summary>
        internal static string noRecord_text {
            get {
                return ResourceManager.GetString("noRecord_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a mode.
        /// </summary>
        internal static string noRecord_title {
            get {
                return ResourceManager.GetString("noRecord_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string onErrorCaution_btn1_label {
            get {
                return ResourceManager.GetString("onErrorCaution_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string onErrorStop_btn1_label {
            get {
                return ResourceManager.GetString("onErrorStop_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string onMessage_btn1_label {
            get {
                return ResourceManager.GetString("onMessage_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string overBudgetNoOverride_btn1_label {
            get {
                return ResourceManager.GetString("overBudgetNoOverride_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string overBudgetNoOverride_btn2_label {
            get {
                return ResourceManager.GetString("overBudgetNoOverride_btn2_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string overBudgetOverride_btn1_label {
            get {
                return ResourceManager.GetString("overBudgetOverride_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string overBudgetOverride_btn2_label {
            get {
                return ResourceManager.GetString("overBudgetOverride_btn2_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : JOURNAL_AMOUNT.
        /// </summary>
        internal static string recurJeData_accountBalance_hint {
            get {
                return ResourceManager.GetString("recurJeData_accountBalance_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Amount.
        /// </summary>
        internal static string recurJeData_accountBalance_label {
            get {
                return ResourceManager.GetString("recurJeData_accountBalance_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Balance.
        /// </summary>
        internal static string recurJeData_accountBalance_prompttext {
            get {
                return ResourceManager.GetString("recurJeData_accountBalance_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : ACCOUNT_ID.
        /// </summary>
        internal static string recurJeData_accountId_hint {
            get {
                return ResourceManager.GetString("recurJeData_accountId_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Id.
        /// </summary>
        internal static string recurJeData_accountId_label {
            get {
                return ResourceManager.GetString("recurJeData_accountId_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : ACCOUNT_NO.
        /// </summary>
        internal static string recurJeData_accountNo_hint {
            get {
                return ResourceManager.GetString("recurJeData_accountNo_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No.
        /// </summary>
        internal static string recurJeData_accountNo_label {
            get {
                return ResourceManager.GetString("recurJeData_accountNo_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No.
        /// </summary>
        internal static string recurJeData_accountNo_prompttext {
            get {
                return ResourceManager.GetString("recurJeData_accountNo_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : JOURNAL_AMOUNT.
        /// </summary>
        internal static string recurJeData_crAmount_hint {
            get {
                return ResourceManager.GetString("recurJeData_crAmount_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Amount.
        /// </summary>
        internal static string recurJeData_crAmount_label {
            get {
                return ResourceManager.GetString("recurJeData_crAmount_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Amount.
        /// </summary>
        internal static string recurJeData_crAmount_prompttext {
            get {
                return ResourceManager.GetString("recurJeData_crAmount_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : DEBIT_CREDIT_FLAG.
        /// </summary>
        internal static string recurJeData_debitCreditFlag_hint {
            get {
                return ResourceManager.GetString("recurJeData_debitCreditFlag_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Credit Flag.
        /// </summary>
        internal static string recurJeData_debitCreditFlag_label {
            get {
                return ResourceManager.GetString("recurJeData_debitCreditFlag_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : JOURNAL_AMOUNT.
        /// </summary>
        internal static string recurJeData_drAmount_hint {
            get {
                return ResourceManager.GetString("recurJeData_drAmount_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Amount.
        /// </summary>
        internal static string recurJeData_drAmount_label {
            get {
                return ResourceManager.GetString("recurJeData_drAmount_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Amount.
        /// </summary>
        internal static string recurJeData_drAmount_prompttext {
            get {
                return ResourceManager.GetString("recurJeData_drAmount_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string recurJeData_drTotal_prompttext {
            get {
                return ResourceManager.GetString("recurJeData_drTotal_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : ACCOUNT_ID.
        /// </summary>
        internal static string recurJeData_holdAccountId_hint {
            get {
                return ResourceManager.GetString("recurJeData_holdAccountId_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Id.
        /// </summary>
        internal static string recurJeData_holdAccountId_label {
            get {
                return ResourceManager.GetString("recurJeData_holdAccountId_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : JOURNAL_AMOUNT.
        /// </summary>
        internal static string recurJeData_holdCrAmount_hint {
            get {
                return ResourceManager.GetString("recurJeData_holdCrAmount_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Amount.
        /// </summary>
        internal static string recurJeData_holdCrAmount_label {
            get {
                return ResourceManager.GetString("recurJeData_holdCrAmount_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Amount.
        /// </summary>
        internal static string recurJeData_holdCrAmount_prompttext {
            get {
                return ResourceManager.GetString("recurJeData_holdCrAmount_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : JOURNAL_AMOUNT.
        /// </summary>
        internal static string recurJeData_holdDrAmount_hint {
            get {
                return ResourceManager.GetString("recurJeData_holdDrAmount_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Amount.
        /// </summary>
        internal static string recurJeData_holdDrAmount_label {
            get {
                return ResourceManager.GetString("recurJeData_holdDrAmount_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Amount.
        /// </summary>
        internal static string recurJeData_holdDrAmount_prompttext {
            get {
                return ResourceManager.GetString("recurJeData_holdDrAmount_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : JOURNAL_AMOUNT.
        /// </summary>
        internal static string recurJeData_holdJournalAmount_hint {
            get {
                return ResourceManager.GetString("recurJeData_holdJournalAmount_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Amount.
        /// </summary>
        internal static string recurJeData_holdJournalAmount_label {
            get {
                return ResourceManager.GetString("recurJeData_holdJournalAmount_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : JOURNAL_AMOUNT.
        /// </summary>
        internal static string recurJeData_journalAmount_hint {
            get {
                return ResourceManager.GetString("recurJeData_journalAmount_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Amount.
        /// </summary>
        internal static string recurJeData_journalAmount_label {
            get {
                return ResourceManager.GetString("recurJeData_journalAmount_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : JOURNAL_DESCRIPTION.
        /// </summary>
        internal static string recurJeData_journalDescription_hint {
            get {
                return ResourceManager.GetString("recurJeData_journalDescription_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Description.
        /// </summary>
        internal static string recurJeData_journalDescription_label {
            get {
                return ResourceManager.GetString("recurJeData_journalDescription_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Description.
        /// </summary>
        internal static string recurJeData_journalDescription_prompttext {
            get {
                return ResourceManager.GetString("recurJeData_journalDescription_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : LINE_NO.
        /// </summary>
        internal static string recurJeData_lineNo_hint {
            get {
                return ResourceManager.GetString("recurJeData_lineNo_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line No.
        /// </summary>
        internal static string recurJeData_lineNo_label {
            get {
                return ResourceManager.GetString("recurJeData_lineNo_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string recurJeData_lineNo_prompttext {
            get {
                return ResourceManager.GetString("recurJeData_lineNo_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : RECUR_JOURNAL_ID.
        /// </summary>
        internal static string recurJeData_recurJournalId_hint {
            get {
                return ResourceManager.GetString("recurJeData_recurJournalId_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recur Journal Id.
        /// </summary>
        internal static string recurJeData_recurJournalId_label {
            get {
                return ResourceManager.GetString("recurJeData_recurJournalId_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resequence.
        /// </summary>
        internal static string recurJeData_resequence_label {
            get {
                return ResourceManager.GetString("recurJeData_resequence_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Chain.
        /// </summary>
        internal static string recurJeHeader_approvalChain_prompttext {
            get {
                return ResourceManager.GetString("recurJeHeader_approvalChain_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring.
        /// </summary>
        internal static string recurJeHeader_assignRecurJournalId_label {
            get {
                return ResourceManager.GetString("recurJeHeader_assignRecurJournalId_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string recurJeHeader_assignReference_label {
            get {
                return ResourceManager.GetString("recurJeHeader_assignReference_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Journal.
        /// </summary>
        internal static string recurJeHeader_createJournal_label {
            get {
                return ResourceManager.GetString("recurJeHeader_createJournal_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : JOURNAL_DATE.
        /// </summary>
        internal static string recurJeHeader_journalDate_hint {
            get {
                return ResourceManager.GetString("recurJeHeader_journalDate_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Date.
        /// </summary>
        internal static string recurJeHeader_journalDate_label {
            get {
                return ResourceManager.GetString("recurJeHeader_journalDate_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string recurJeHeader_journalDate_prompttext {
            get {
                return ResourceManager.GetString("recurJeHeader_journalDate_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Date.
        /// </summary>
        internal static string recurJeHeader_journalDate_title {
            get {
                return ResourceManager.GetString("recurJeHeader_journalDate_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-Click for Calendar.
        /// </summary>
        internal static string recurJeHeader_journalDate_tooltip {
            get {
                return ResourceManager.GetString("recurJeHeader_journalDate_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : JOURNAL_DESCRIPTION.
        /// </summary>
        internal static string recurJeHeader_journalDescription_hint {
            get {
                return ResourceManager.GetString("recurJeHeader_journalDescription_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Description.
        /// </summary>
        internal static string recurJeHeader_journalDescription_label {
            get {
                return ResourceManager.GetString("recurJeHeader_journalDescription_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready for Approval.
        /// </summary>
        internal static string recurJeHeader_readyForApproval_label {
            get {
                return ResourceManager.GetString("recurJeHeader_readyForApproval_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : RECUR_JOURNAL_DESC.
        /// </summary>
        internal static string recurJeHeader_recurJournalDesc_hint {
            get {
                return ResourceManager.GetString("recurJeHeader_recurJournalDesc_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring Description.
        /// </summary>
        internal static string recurJeHeader_recurJournalDesc_label {
            get {
                return ResourceManager.GetString("recurJeHeader_recurJournalDesc_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string recurJeHeader_recurJournalDesc_title {
            get {
                return ResourceManager.GetString("recurJeHeader_recurJournalDesc_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : RECUR_JOURNAL_ID.
        /// </summary>
        internal static string recurJeHeader_recurJournalId_hint {
            get {
                return ResourceManager.GetString("recurJeHeader_recurJournalId_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring Journal Id.
        /// </summary>
        internal static string recurJeHeader_recurJournalId_label {
            get {
                return ResourceManager.GetString("recurJeHeader_recurJournalId_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring.
        /// </summary>
        internal static string recurJeHeader_recurJournalId_title {
            get {
                return ResourceManager.GetString("recurJeHeader_recurJournalId_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : REFERENCE_NO.
        /// </summary>
        internal static string recurJeHeader_referenceNo_hint {
            get {
                return ResourceManager.GetString("recurJeHeader_referenceNo_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference No.
        /// </summary>
        internal static string recurJeHeader_referenceNo_label {
            get {
                return ResourceManager.GetString("recurJeHeader_referenceNo_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference No.
        /// </summary>
        internal static string recurJeHeader_referenceNo_title {
            get {
                return ResourceManager.GetString("recurJeHeader_referenceNo_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring Journal Entries.
        /// </summary>
        internal static string recurJeHeader_title {
            get {
                return ResourceManager.GetString("recurJeHeader_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero Amounts.
        /// </summary>
        internal static string recurJeHeader_zeroAmounts_label {
            get {
                return ResourceManager.GetString("recurJeHeader_zeroAmounts_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring Journal Entries.
        /// </summary>
        internal static string recurJournalEntry_title {
            get {
                return ResourceManager.GetString("recurJournalEntry_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string zeroAmounts_btn1_label {
            get {
                return ResourceManager.GetString("zeroAmounts_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string zeroAmounts_btn2_label {
            get {
                return ResourceManager.GetString("zeroAmounts_btn2_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to zero out all the journal amounts on the screen?.
        /// </summary>
        internal static string zeroAmounts_text {
            get {
                return ResourceManager.GetString("zeroAmounts_text", resourceCulture);
            }
        }
    }
}
