
//----------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------------------
using Foundations.Core.AppSupportLib.Runtime.ControlsModel;
using Foundations.Core.AppSupportLib.Runtime.ControlsModel.Containers;
using Foundations.Core.AppSupportLib.Runtime.ControlsModel.Alerts;
using Foundations.Core.AppSupportLib.Runtime.ControlsModel.Lovs;
using Foundations.Flavors.Forms;
using Foundations.Flavors.Forms.Descriptors;
using Foundations.Core.AppSupportLib.Runtime.Task;
using Foundations.Core.AppSupportLib.Composition;
using System.Globalization;

namespace Alio.Forms.Slact01a
{	
 
	public partial class Slact01aTaskBlocks
	{ 
		public Slact01aTaskBlocks(Slact01aTask task)
		{
			Accounts = new AccountsBlockDescriptor(task);
			NickAccounts = new NickAccountsBlockDescriptor(task);
			Controls = new ControlsBlockDescriptor(task);
		}		

		public AccountsBlockDescriptor Accounts { get; private set; }
		public NickAccountsBlockDescriptor NickAccounts { get; private set; }
		public ControlsBlockDescriptor Controls { get; private set; }


		public class AccountsBlockDescriptor : BlockDescriptorWrapper
        {
            public AccountsBlockDescriptor(AbstractTask task) : base("ACCOUNTS", task)
            {
                Items = new AccountsItems(this);
            }
            public AccountsItems Items { get; private set; }

            public class AccountsItems
            {
                public AccountsItems(BlockDescriptorWrapper block)
                {
					AccountNo = block.FindItem("ACCOUNT_NO");
					AccountId = block.FindItem("ACCOUNT_ID");
					AccountYear = block.FindItem("ACCOUNT_YEAR");
					AccountDesc = block.FindItem("ACCOUNT_DESC");
 
                }

				public ItemDescriptorWrapper AccountNo { get; private set; }
				public ItemDescriptorWrapper AccountId { get; private set; }
				public ItemDescriptorWrapper AccountYear { get; private set; }
				public ItemDescriptorWrapper AccountDesc { get; private set; }
 
            }
        }
		public class NickAccountsBlockDescriptor : BlockDescriptorWrapper
        {
            public NickAccountsBlockDescriptor(AbstractTask task) : base("NICK_ACCOUNTS", task)
            {
                Items = new NickAccountsItems(this);
            }
            public NickAccountsItems Items { get; private set; }

            public class NickAccountsItems
            {
                public NickAccountsItems(BlockDescriptorWrapper block)
                {
					AccountNickNo = block.FindItem("ACCOUNT_NICK_NO");
					UserId = block.FindItem("USER_ID");
					SysGenFlag = block.FindItem("SYS_GEN_FLAG");
					AccountId = block.FindItem("ACCOUNT_ID");
 
                }

				public ItemDescriptorWrapper AccountNickNo { get; private set; }
				public ItemDescriptorWrapper UserId { get; private set; }
				public ItemDescriptorWrapper SysGenFlag { get; private set; }
				public ItemDescriptorWrapper AccountId { get; private set; }
 
            }
        }
		public class ControlsBlockDescriptor : BlockDescriptorWrapper
        {
            public ControlsBlockDescriptor(AbstractTask task) : base("CONTROLS", task)
            {
                Items = new ControlsItems(this);
            }
            public ControlsItems Items { get; private set; }

            public class ControlsItems
            {
                public ControlsItems(BlockDescriptorWrapper block)
                {
					Button01 = block.FindItem("BUTTON_01");
					Button02 = block.FindItem("BUTTON_02");
					Button03 = block.FindItem("BUTTON_03");
					Button04 = block.FindItem("BUTTON_04");
					Button05 = block.FindItem("BUTTON_05");
					Button06 = block.FindItem("BUTTON_06");
					Button07 = block.FindItem("BUTTON_07");
					Button08 = block.FindItem("BUTTON_08");
					MainMenu = block.FindItem("MAIN_MENU");
					Close = block.FindItem("CLOSE");
					ProgramList = block.FindItem("PROGRAM_LIST");
					Go = block.FindItem("GO");
					ScreenMode = block.FindItem("SCREEN_MODE");
					QtsiFindFlag = block.FindItem("QTSI_FIND_FLAG");
					QtsiAddFlag = block.FindItem("QTSI_ADD_FLAG");
					QtsiDeleteFlag = block.FindItem("QTSI_DELETE_FLAG");
					QtsiUpdateFlag = block.FindItem("QTSI_UPDATE_FLAG");
 
                }

				public ItemDescriptorWrapper Button01 { get; private set; }
				public ItemDescriptorWrapper Button02 { get; private set; }
				public ItemDescriptorWrapper Button03 { get; private set; }
				public ItemDescriptorWrapper Button04 { get; private set; }
				public ItemDescriptorWrapper Button05 { get; private set; }
				public ItemDescriptorWrapper Button06 { get; private set; }
				public ItemDescriptorWrapper Button07 { get; private set; }
				public ItemDescriptorWrapper Button08 { get; private set; }
				public ItemDescriptorWrapper MainMenu { get; private set; }
				public ItemDescriptorWrapper Close { get; private set; }
				public ItemDescriptorWrapper ProgramList { get; private set; }
				public ItemDescriptorWrapper Go { get; private set; }
				public ItemDescriptorWrapper ScreenMode { get; private set; }
				public ItemDescriptorWrapper QtsiFindFlag { get; private set; }
				public ItemDescriptorWrapper QtsiAddFlag { get; private set; }
				public ItemDescriptorWrapper QtsiDeleteFlag { get; private set; }
				public ItemDescriptorWrapper QtsiUpdateFlag { get; private set; }
 
            }
        }
 
	}
  

	public partial class Slact01aTaskWindows 
	{ 
		public Slact01aTaskWindows(Slact01aTask task)
		{
			AccountLookup = new WindowDescriptorWrapper(task.FindWindow("ACCOUNT_LOOKUP"));
		}
		public WindowDescriptor AccountLookup { get; private set; }
	}

	public partial class Slact01aTaskCanvases
	{ 
		public Slact01aTaskCanvases(Slact01aTask task)
		{
			AccountLookup = new CanvasDescriptorWrapper(task.FindCanvas("ACCOUNT_LOOKUP"));
			Controls = new CanvasDescriptorWrapper(task.FindCanvas("CONTROLS"));
		}
		public CanvasDescriptor AccountLookup { get; private set; }
		public CanvasDescriptor Controls { get; private set; }
  
	}
  

	public partial class Slact01aTaskAlerts
	{ 
		public Slact01aTaskAlerts(Slact01aTask task)
		{
			NoRecord = new AlertDescriptorWrapper(task.FindAlert("NO_RECORD"));
			OnMessage = new AlertDescriptorWrapper(task.FindAlert("ON_MESSAGE"));
			OnErrorCaution = new AlertDescriptorWrapper(task.FindAlert("ON_ERROR_CAUTION"));
			OnErrorStop = new AlertDescriptorWrapper(task.FindAlert("ON_ERROR_STOP"));
		}
		public AlertDescriptor NoRecord { get; private set; }
		public AlertDescriptor OnMessage { get; private set; }
		public AlertDescriptor OnErrorCaution { get; private set; }
		public AlertDescriptor OnErrorStop { get; private set; }
  
	}
  

	public partial class Slact01aTaskLovs
	{ 
		public Slact01aTaskLovs(Slact01aTask task)
		{
			AccountsLov = new LovDescriptorWrapper(task.FindLov("ACCOUNTS_LOV"));
		}
		public LovDescriptor AccountsLov { get; private set; }
  
	}
  
}
  