//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alio.Forms.Fmbth01a.Views.locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alio.Forms.Fmbth01a.Views.locales.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string accountPeriodChange_btn1_label {
            get {
                return ResourceManager.GetString("accountPeriodChange_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string accountPeriodChange_btn2_label {
            get {
                return ResourceManager.GetString("accountPeriodChange_btn2_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account period is not the default. Do you want to revert to the default accounting period?.
        /// </summary>
        internal static string accountPeriodChange_text {
            get {
                return ResourceManager.GetString("accountPeriodChange_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string accountPeriodWarning_btn1_label {
            get {
                return ResourceManager.GetString("accountPeriodWarning_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string accountPeriodWarning_btn2_label {
            get {
                return ResourceManager.GetString("accountPeriodWarning_btn2_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This date is not in the valid range for&amp;#xA;this account period click ok to continue.
        /// </summary>
        internal static string accountPeriodWarning_text {
            get {
                return ResourceManager.GetString("accountPeriodWarning_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : ACCESS_FLAG.
        /// </summary>
        internal static string batches_accessFlag_hint {
            get {
                return ResourceManager.GetString("batches_accessFlag_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Flag.
        /// </summary>
        internal static string batches_accessFlag_label {
            get {
                return ResourceManager.GetString("batches_accessFlag_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : ACCOUNT_PERIOD.
        /// </summary>
        internal static string batches_accountPeriod_hint {
            get {
                return ResourceManager.GetString("batches_accountPeriod_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Period.
        /// </summary>
        internal static string batches_accountPeriod_label {
            get {
                return ResourceManager.GetString("batches_accountPeriod_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting&amp;#xA;Period.
        /// </summary>
        internal static string batches_accountPeriod_prompttext {
            get {
                return ResourceManager.GetString("batches_accountPeriod_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch.
        /// </summary>
        internal static string batches_assignBatch_label {
            get {
                return ResourceManager.GetString("batches_assignBatch_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warrant.
        /// </summary>
        internal static string batches_assignWarrant_label {
            get {
                return ResourceManager.GetString("batches_assignWarrant_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : BATCH_DATE.
        /// </summary>
        internal static string batches_batchDate_hint {
            get {
                return ResourceManager.GetString("batches_batchDate_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Date.
        /// </summary>
        internal static string batches_batchDate_label {
            get {
                return ResourceManager.GetString("batches_batchDate_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction&amp;#xA;Date.
        /// </summary>
        internal static string batches_batchDate_prompttext {
            get {
                return ResourceManager.GetString("batches_batchDate_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-Click for Calendar.
        /// </summary>
        internal static string batches_batchDate_tooltip {
            get {
                return ResourceManager.GetString("batches_batchDate_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : BATCH_DESCRIPTION.
        /// </summary>
        internal static string batches_batchDescription_hint {
            get {
                return ResourceManager.GetString("batches_batchDescription_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Description.
        /// </summary>
        internal static string batches_batchDescription_label {
            get {
                return ResourceManager.GetString("batches_batchDescription_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string batches_batchDescription_prompttext {
            get {
                return ResourceManager.GetString("batches_batchDescription_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use This Batch.
        /// </summary>
        internal static string batches_batchLovBtn_label {
            get {
                return ResourceManager.GetString("batches_batchLovBtn_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Master Listing.
        /// </summary>
        internal static string batches_batchMasterListing_label {
            get {
                return ResourceManager.GetString("batches_batchMasterListing_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : BATCH_NO.
        /// </summary>
        internal static string batches_batchNo_hint {
            get {
                return ResourceManager.GetString("batches_batchNo_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch.
        /// </summary>
        internal static string batches_batchNo_label {
            get {
                return ResourceManager.GetString("batches_batchNo_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : BATCH_ORIGIN.
        /// </summary>
        internal static string batches_batchOrigin_hint {
            get {
                return ResourceManager.GetString("batches_batchOrigin_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Origin.
        /// </summary>
        internal static string batches_batchOrigin_label {
            get {
                return ResourceManager.GetString("batches_batchOrigin_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : BATCH_TYPE.
        /// </summary>
        internal static string batches_batchType_hint {
            get {
                return ResourceManager.GetString("batches_batchType_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Type.
        /// </summary>
        internal static string batches_batchType_label {
            get {
                return ResourceManager.GetString("batches_batchType_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : ACCOUNT_YEAR.
        /// </summary>
        internal static string batches_batchYear_hint {
            get {
                return ResourceManager.GetString("batches_batchYear_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Year.
        /// </summary>
        internal static string batches_batchYear_label {
            get {
                return ResourceManager.GetString("batches_batchYear_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : DATE_CREATED.
        /// </summary>
        internal static string batches_dateCreated_hint {
            get {
                return ResourceManager.GetString("batches_dateCreated_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Created.
        /// </summary>
        internal static string batches_dateCreated_label {
            get {
                return ResourceManager.GetString("batches_dateCreated_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-Click for Calendar.
        /// </summary>
        internal static string batches_dateCreated_tooltip {
            get {
                return ResourceManager.GetString("batches_dateCreated_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string batches_details_label {
            get {
                return ResourceManager.GetString("batches_details_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : POSTED_FLAG.
        /// </summary>
        internal static string batches_postedFlag_hint {
            get {
                return ResourceManager.GetString("batches_postedFlag_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Active Batch.
        /// </summary>
        internal static string batches_resetActiveBatch_label {
            get {
                return ResourceManager.GetString("batches_resetActiveBatch_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string batches_status_prompttext {
            get {
                return ResourceManager.GetString("batches_status_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTRY -- Edit has not been run  ERROR -- Edit was run and errors were found  READY -- Edit has been run and batch is ready to post.
        /// </summary>
        internal static string batches_status_tooltip {
            get {
                return ResourceManager.GetString("batches_status_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Master.
        /// </summary>
        internal static string batches_title {
            get {
                return ResourceManager.GetString("batches_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : USER_ID.
        /// </summary>
        internal static string batches_userId_hint {
            get {
                return ResourceManager.GetString("batches_userId_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string batches_userId_label {
            get {
                return ResourceManager.GetString("batches_userId_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string batches_userId_prompttext {
            get {
                return ResourceManager.GetString("batches_userId_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string batches_useThisBatch_label {
            get {
                return ResourceManager.GetString("batches_useThisBatch_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : BATCH_NO.
        /// </summary>
        internal static string batches_warrantFromDate_hint {
            get {
                return ResourceManager.GetString("batches_warrantFromDate_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch.
        /// </summary>
        internal static string batches_warrantFromDate_label {
            get {
                return ResourceManager.GetString("batches_warrantFromDate_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From&amp;#xA;Date.
        /// </summary>
        internal static string batches_warrantFromDate_prompttext {
            get {
                return ResourceManager.GetString("batches_warrantFromDate_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use This Batch.
        /// </summary>
        internal static string batches_warrantLovBtn_label {
            get {
                return ResourceManager.GetString("batches_warrantLovBtn_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : BATCH_NO.
        /// </summary>
        internal static string batches_warrantToDate_hint {
            get {
                return ResourceManager.GetString("batches_warrantToDate_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch.
        /// </summary>
        internal static string batches_warrantToDate_label {
            get {
                return ResourceManager.GetString("batches_warrantToDate_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To&amp;#xA;Date.
        /// </summary>
        internal static string batches_warrantToDate_prompttext {
            get {
                return ResourceManager.GetString("batches_warrantToDate_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Key.
        /// </summary>
        internal static string batchNoLov_keyValue_title {
            get {
                return ResourceManager.GetString("batchNoLov_keyValue_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BATCH_NO.
        /// </summary>
        internal static string batchNoLov_title {
            get {
                return ResourceManager.GetString("batchNoLov_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string batchPrefix_btn1_label {
            get {
                return ResourceManager.GetString("batchPrefix_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string batchPrefix_btn2_label {
            get {
                return ResourceManager.GetString("batchPrefix_btn2_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string batchPrefix_btn3_label {
            get {
                return ResourceManager.GetString("batchPrefix_btn3_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date List of Values.
        /// </summary>
        internal static string dateLovWindow_title {
            get {
                return ResourceManager.GetString("dateLovWindow_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string debugMessage_btn1_label {
            get {
                return ResourceManager.GetString("debugMessage_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Debug.
        /// </summary>
        internal static string debugMessage_btn2_label {
            get {
                return ResourceManager.GetString("debugMessage_btn2_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Message.
        /// </summary>
        internal static string debugMessage_title {
            get {
                return ResourceManager.GetString("debugMessage_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : ACCOUNT_PERIOD.
        /// </summary>
        internal static string hold_accountPeriod_hint {
            get {
                return ResourceManager.GetString("hold_accountPeriod_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Period.
        /// </summary>
        internal static string hold_accountPeriod_label {
            get {
                return ResourceManager.GetString("hold_accountPeriod_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string noRecord_btn1_label {
            get {
                return ResourceManager.GetString("noRecord_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string noRecord_btn2_label {
            get {
                return ResourceManager.GetString("noRecord_btn2_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were no records found - Please choose a mode.
        /// </summary>
        internal static string noRecord_text {
            get {
                return ResourceManager.GetString("noRecord_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a mode.
        /// </summary>
        internal static string noRecord_title {
            get {
                return ResourceManager.GetString("noRecord_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string onErrorCaution_btn1_label {
            get {
                return ResourceManager.GetString("onErrorCaution_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string onErrorStop_btn1_label {
            get {
                return ResourceManager.GetString("onErrorStop_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string onMessage_btn1_label {
            get {
                return ResourceManager.GetString("onMessage_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string saveChanges_btn1_label {
            get {
                return ResourceManager.GetString("saveChanges_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string saveChanges_btn2_label {
            get {
                return ResourceManager.GetString("saveChanges_btn2_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string saveChanges_btn3_label {
            get {
                return ResourceManager.GetString("saveChanges_btn3_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Want to Save The Changes You Have Made?.
        /// </summary>
        internal static string saveChanges_text {
            get {
                return ResourceManager.GetString("saveChanges_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string warrantNoLov_batchDescription_title {
            get {
                return ResourceManager.GetString("warrantNoLov_batchDescription_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        internal static string warrantNoLov_fromDate_title {
            get {
                return ResourceManager.GetString("warrantNoLov_fromDate_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warrants.
        /// </summary>
        internal static string warrantNoLov_title {
            get {
                return ResourceManager.GetString("warrantNoLov_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        internal static string warrantNoLov_toDate_title {
            get {
                return ResourceManager.GetString("warrantNoLov_toDate_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warrant.
        /// </summary>
        internal static string warrantNoLov_warrantNo_title {
            get {
                return ResourceManager.GetString("warrantNoLov_warrantNo_title", resourceCulture);
            }
        }
    }
}
