//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alio.Forms.Fjapp01a.Views.locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alio.Forms.Fjapp01a.Views.locales.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AJE Approval.
        /// </summary>
        internal static string ajeApproval_label {
            get {
                return ResourceManager.GetString("ajeApproval_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AJE Approval.
        /// </summary>
        internal static string ajeApproval_title {
            get {
                return ResourceManager.GetString("ajeApproval_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Chain.
        /// </summary>
        internal static string approvalChain_label {
            get {
                return ResourceManager.GetString("approvalChain_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date List of Values.
        /// </summary>
        internal static string dateLovWindow_title {
            get {
                return ResourceManager.GetString("dateLovWindow_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Save As Is.
        /// </summary>
        internal static string debitCredit_btn1_label {
            get {
                return ResourceManager.GetString("debitCredit_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, Edit Entries.
        /// </summary>
        internal static string debitCredit_btn2_label {
            get {
                return ResourceManager.GetString("debitCredit_btn2_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit and Credit Totals do not match! 
        ///(Out of balance journal entries will not post) 
        ///Do you want to save anyway? .
        /// </summary>
        internal static string debitCredit_text {
            get {
                return ResourceManager.GetString("debitCredit_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Balance.
        /// </summary>
        internal static string debitCredit_title {
            get {
                return ResourceManager.GetString("debitCredit_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : JOURNAL_AMOUNT.
        /// </summary>
        internal static string jeData_accountBalance_hint {
            get {
                return ResourceManager.GetString("jeData_accountBalance_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Amount.
        /// </summary>
        internal static string jeData_accountBalance_label {
            get {
                return ResourceManager.GetString("jeData_accountBalance_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Balance.
        /// </summary>
        internal static string jeData_accountBalance_prompttext {
            get {
                return ResourceManager.GetString("jeData_accountBalance_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : ACCOUNT_ID.
        /// </summary>
        internal static string jeData_accountId_hint {
            get {
                return ResourceManager.GetString("jeData_accountId_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account ID.
        /// </summary>
        internal static string jeData_accountId_label {
            get {
                return ResourceManager.GetString("jeData_accountId_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : JOURNAL_AMOUNT.
        /// </summary>
        internal static string jeData_crAmount_hint {
            get {
                return ResourceManager.GetString("jeData_crAmount_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Amount.
        /// </summary>
        internal static string jeData_crAmount_label {
            get {
                return ResourceManager.GetString("jeData_crAmount_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Amount.
        /// </summary>
        internal static string jeData_crAmount_prompttext {
            get {
                return ResourceManager.GetString("jeData_crAmount_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : DEBIT_CREDIT_FLAG.
        /// </summary>
        internal static string jeData_debitCreditFlag_hint {
            get {
                return ResourceManager.GetString("jeData_debitCreditFlag_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Credit Flag.
        /// </summary>
        internal static string jeData_debitCreditFlag_label {
            get {
                return ResourceManager.GetString("jeData_debitCreditFlag_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number / Description.
        /// </summary>
        internal static string jeData_displayAccount_prompttext {
            get {
                return ResourceManager.GetString("jeData_displayAccount_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : JOURNAL_AMOUNT.
        /// </summary>
        internal static string jeData_drAmount_hint {
            get {
                return ResourceManager.GetString("jeData_drAmount_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Amount.
        /// </summary>
        internal static string jeData_drAmount_label {
            get {
                return ResourceManager.GetString("jeData_drAmount_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Amount.
        /// </summary>
        internal static string jeData_drAmount_prompttext {
            get {
                return ResourceManager.GetString("jeData_drAmount_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string jeData_drTotal_prompttext {
            get {
                return ResourceManager.GetString("jeData_drTotal_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : LINE_NO.
        /// </summary>
        internal static string jeData_lineNo_hint {
            get {
                return ResourceManager.GetString("jeData_lineNo_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string jeData_lineNo_label {
            get {
                return ResourceManager.GetString("jeData_lineNo_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : REFERENCE_NO.
        /// </summary>
        internal static string jeData_referenceNo_hint {
            get {
                return ResourceManager.GetString("jeData_referenceNo_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string jeData_referenceNo_label {
            get {
                return ResourceManager.GetString("jeData_referenceNo_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string jeHeader_approve_label {
            get {
                return ResourceManager.GetString("jeHeader_approve_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve this budget request and update approval chain..
        /// </summary>
        internal static string jeHeader_approve_tooltip {
            get {
                return ResourceManager.GetString("jeHeader_approve_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : DATE_TO_PAY.
        /// </summary>
        internal static string jeHeader_batchDate_hint {
            get {
                return ResourceManager.GetString("jeHeader_batchDate_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date to Pay.
        /// </summary>
        internal static string jeHeader_batchDate_label {
            get {
                return ResourceManager.GetString("jeHeader_batchDate_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string jeHeader_batchDate_prompttext {
            get {
                return ResourceManager.GetString("jeHeader_batchDate_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-Click for Calendar.
        /// </summary>
        internal static string jeHeader_batchDate_tooltip {
            get {
                return ResourceManager.GetString("jeHeader_batchDate_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : BATCH_NO.
        /// </summary>
        internal static string jeHeader_batchNo_hint {
            get {
                return ResourceManager.GetString("jeHeader_batchNo_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch.
        /// </summary>
        internal static string jeHeader_batchNo_label {
            get {
                return ResourceManager.GetString("jeHeader_batchNo_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch.
        /// </summary>
        internal static string jeHeader_batchNo_prompttext {
            get {
                return ResourceManager.GetString("jeHeader_batchNo_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Year.
        /// </summary>
        internal static string jeHeader_batchYear_prompttext {
            get {
                return ResourceManager.GetString("jeHeader_batchYear_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string jeHeader_disapprovalEdit_label {
            get {
                return ResourceManager.GetString("jeHeader_disapprovalEdit_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disapproval Reason.
        /// </summary>
        internal static string jeHeader_disapprovalMessage_prompttext {
            get {
                return ResourceManager.GetString("jeHeader_disapprovalMessage_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disapprove.
        /// </summary>
        internal static string jeHeader_disapprove_label {
            get {
                return ResourceManager.GetString("jeHeader_disapprove_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disapprove this budget request..
        /// </summary>
        internal static string jeHeader_disapprove_tooltip {
            get {
                return ResourceManager.GetString("jeHeader_disapprove_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : JOURNAL_DESCRIPTION.
        /// </summary>
        internal static string jeHeader_journalDescription_hint {
            get {
                return ResourceManager.GetString("jeHeader_journalDescription_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Description.
        /// </summary>
        internal static string jeHeader_journalDescription_label {
            get {
                return ResourceManager.GetString("jeHeader_journalDescription_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string jeHeader_journalDescription_prompttext {
            get {
                return ResourceManager.GetString("jeHeader_journalDescription_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : REFERENCE_NO.
        /// </summary>
        internal static string jeHeader_referenceNo_hint {
            get {
                return ResourceManager.GetString("jeHeader_referenceNo_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string jeHeader_referenceNo_label {
            get {
                return ResourceManager.GetString("jeHeader_referenceNo_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string jeHeader_referenceNo_prompttext {
            get {
                return ResourceManager.GetString("jeHeader_referenceNo_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requestor.
        /// </summary>
        internal static string jeHeader_requestor_prompttext {
            get {
                return ResourceManager.GetString("jeHeader_requestor_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string jeHeader_userName_prompttext {
            get {
                return ResourceManager.GetString("jeHeader_userName_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Code&amp;#xA;Description .
        /// </summary>
        internal static string journalApproval_appCodeDesc_prompttext {
            get {
                return ResourceManager.GetString("journalApproval_appCodeDesc_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval&amp;#xA;Code.
        /// </summary>
        internal static string journalApproval_approvalCode_prompttext {
            get {
                return ResourceManager.GetString("journalApproval_approvalCode_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver&amp;#xA;Sequence.
        /// </summary>
        internal static string journalApproval_approverSequence_prompttext {
            get {
                return ResourceManager.GetString("journalApproval_approverSequence_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string journalApproval_referenceNo_prompttext {
            get {
                return ResourceManager.GetString("journalApproval_referenceNo_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Date.
        /// </summary>
        internal static string journalApproval_statusDate_prompttext {
            get {
                return ResourceManager.GetString("journalApproval_statusDate_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status&amp;#xA;Description .
        /// </summary>
        internal static string journalApproval_statusDescription_prompttext {
            get {
                return ResourceManager.GetString("journalApproval_statusDescription_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string journalApproval_statusFlag_prompttext {
            get {
                return ResourceManager.GetString("journalApproval_statusFlag_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string journalApproval_userId_prompttext {
            get {
                return ResourceManager.GetString("journalApproval_userId_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string noRecord_btn1_label {
            get {
                return ResourceManager.GetString("noRecord_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string noRecord_btn2_label {
            get {
                return ResourceManager.GetString("noRecord_btn2_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were no records found - Please choose a mode.
        /// </summary>
        internal static string noRecord_text {
            get {
                return ResourceManager.GetString("noRecord_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a mode.
        /// </summary>
        internal static string noRecord_title {
            get {
                return ResourceManager.GetString("noRecord_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string onErrorCaution_btn1_label {
            get {
                return ResourceManager.GetString("onErrorCaution_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string onErrorStop_btn1_label {
            get {
                return ResourceManager.GetString("onErrorStop_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string onMessage_btn1_label {
            get {
                return ResourceManager.GetString("onMessage_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Date.
        /// </summary>
        internal static string pendingApprovalsLov_batchDate_title {
            get {
                return ResourceManager.GetString("pendingApprovalsLov_batchDate_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Description.
        /// </summary>
        internal static string pendingApprovalsLov_batchDescription_title {
            get {
                return ResourceManager.GetString("pendingApprovalsLov_batchDescription_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch.
        /// </summary>
        internal static string pendingApprovalsLov_batchNo_title {
            get {
                return ResourceManager.GetString("pendingApprovalsLov_batchNo_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Yr.
        /// </summary>
        internal static string pendingApprovalsLov_batchYear_title {
            get {
                return ResourceManager.GetString("pendingApprovalsLov_batchYear_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string pendingApprovalsLov_referenceNo_title {
            get {
                return ResourceManager.GetString("pendingApprovalsLov_referenceNo_title", resourceCulture);
            }
        }
    }
}
