//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alio.Forms.Fjpst01a.Views.locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alio.Forms.Fjpst01a.Views.locales.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : ACCESS_FLAG.
        /// </summary>
        internal static string batches_accessFlag_hint {
            get {
                return ResourceManager.GetString("batches_accessFlag_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Flag.
        /// </summary>
        internal static string batches_accessFlag_label {
            get {
                return ResourceManager.GetString("batches_accessFlag_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : ACCOUNT_PERIOD.
        /// </summary>
        internal static string batches_accountPeriod_hint {
            get {
                return ResourceManager.GetString("batches_accountPeriod_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Period.
        /// </summary>
        internal static string batches_accountPeriod_label {
            get {
                return ResourceManager.GetString("batches_accountPeriod_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting&amp;#xA;Period.
        /// </summary>
        internal static string batches_accountPeriod_prompttext {
            get {
                return ResourceManager.GetString("batches_accountPeriod_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : BATCH_DATE.
        /// </summary>
        internal static string batches_batchDate_hint {
            get {
                return ResourceManager.GetString("batches_batchDate_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Date.
        /// </summary>
        internal static string batches_batchDate_label {
            get {
                return ResourceManager.GetString("batches_batchDate_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Date.
        /// </summary>
        internal static string batches_batchDate_prompttext {
            get {
                return ResourceManager.GetString("batches_batchDate_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : BATCH_DESCRIPTION.
        /// </summary>
        internal static string batches_batchDescription_hint {
            get {
                return ResourceManager.GetString("batches_batchDescription_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Description.
        /// </summary>
        internal static string batches_batchDescription_label {
            get {
                return ResourceManager.GetString("batches_batchDescription_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string batches_batchDescription_prompttext {
            get {
                return ResourceManager.GetString("batches_batchDescription_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : BATCH_NO.
        /// </summary>
        internal static string batches_batchNo_hint {
            get {
                return ResourceManager.GetString("batches_batchNo_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch.
        /// </summary>
        internal static string batches_batchNo_label {
            get {
                return ResourceManager.GetString("batches_batchNo_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch.
        /// </summary>
        internal static string batches_batchNo_prompttext {
            get {
                return ResourceManager.GetString("batches_batchNo_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : BATCH_ORIGIN.
        /// </summary>
        internal static string batches_batchOrigin_hint {
            get {
                return ResourceManager.GetString("batches_batchOrigin_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Origin.
        /// </summary>
        internal static string batches_batchOrigin_label {
            get {
                return ResourceManager.GetString("batches_batchOrigin_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : BATCH_TYPE.
        /// </summary>
        internal static string batches_batchType_hint {
            get {
                return ResourceManager.GetString("batches_batchType_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Type.
        /// </summary>
        internal static string batches_batchType_label {
            get {
                return ResourceManager.GetString("batches_batchType_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : ACCOUNT_YEAR.
        /// </summary>
        internal static string batches_batchYear_hint {
            get {
                return ResourceManager.GetString("batches_batchYear_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Year.
        /// </summary>
        internal static string batches_batchYear_label {
            get {
                return ResourceManager.GetString("batches_batchYear_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch&amp;#xA;Year.
        /// </summary>
        internal static string batches_batchYear_prompttext {
            get {
                return ResourceManager.GetString("batches_batchYear_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Total.
        /// </summary>
        internal static string batches_creditTotal_prompttext {
            get {
                return ResourceManager.GetString("batches_creditTotal_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : DATE_CREATED.
        /// </summary>
        internal static string batches_dateCreated_hint {
            get {
                return ResourceManager.GetString("batches_dateCreated_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Created.
        /// </summary>
        internal static string batches_dateCreated_label {
            get {
                return ResourceManager.GetString("batches_dateCreated_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Total.
        /// </summary>
        internal static string batches_debitTotal_prompttext {
            get {
                return ResourceManager.GetString("batches_debitTotal_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string batches_details_label {
            get {
                return ResourceManager.GetString("batches_details_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post&amp;#xA;Batch.
        /// </summary>
        internal static string batches_postBatch_prompttext {
            get {
                return ResourceManager.GetString("batches_postBatch_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : POSTED_FLAG.
        /// </summary>
        internal static string batches_postedFlag_hint {
            get {
                return ResourceManager.GetString("batches_postedFlag_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : USER_ID.
        /// </summary>
        internal static string batches_userId_hint {
            get {
                return ResourceManager.GetString("batches_userId_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string batches_userId_label {
            get {
                return ResourceManager.GetString("batches_userId_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string noRecord_btn1_label {
            get {
                return ResourceManager.GetString("noRecord_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string noRecord_btn2_label {
            get {
                return ResourceManager.GetString("noRecord_btn2_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were no records found - Please choose a mode.
        /// </summary>
        internal static string noRecord_text {
            get {
                return ResourceManager.GetString("noRecord_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a mode.
        /// </summary>
        internal static string noRecord_title {
            get {
                return ResourceManager.GetString("noRecord_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string okCancel_cancel_label {
            get {
                return ResourceManager.GetString("okCancel_cancel_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        internal static string okCancel_post_label {
            get {
                return ResourceManager.GetString("okCancel_post_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check / Uncheck All.
        /// </summary>
        internal static string okCancel_selectAll_prompttext {
            get {
                return ResourceManager.GetString("okCancel_selectAll_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string onErrorCaution_btn1_label {
            get {
                return ResourceManager.GetString("onErrorCaution_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string onErrorStop_btn1_label {
            get {
                return ResourceManager.GetString("onErrorStop_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string onMessage_btn1_label {
            get {
                return ResourceManager.GetString("onMessage_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Journal Entries.
        /// </summary>
        internal static string postJeData_title {
            get {
                return ResourceManager.GetString("postJeData_title", resourceCulture);
            }
        }
    }
}
