//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alio.Forms.Slact01a.Views.locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alio.Forms.Slact01a.Views.locales.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Lookup.
        /// </summary>
        internal static string accountLookup_title {
            get {
                return ResourceManager.GetString("accountLookup_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : ACCOUNT_DESC.
        /// </summary>
        internal static string accounts_accountDesc_hint {
            get {
                return ResourceManager.GetString("accounts_accountDesc_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Desc.
        /// </summary>
        internal static string accounts_accountDesc_label {
            get {
                return ResourceManager.GetString("accounts_accountDesc_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : ACCOUNT_ID.
        /// </summary>
        internal static string accounts_accountId_hint {
            get {
                return ResourceManager.GetString("accounts_accountId_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account ID.
        /// </summary>
        internal static string accounts_accountId_label {
            get {
                return ResourceManager.GetString("accounts_accountId_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Lookup.
        /// </summary>
        internal static string accounts_accountId_prompttext {
            get {
                return ResourceManager.GetString("accounts_accountId_prompttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : ACCOUNT_NO.
        /// </summary>
        internal static string accounts_accountNo_hint {
            get {
                return ResourceManager.GetString("accounts_accountNo_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No.
        /// </summary>
        internal static string accounts_accountNo_label {
            get {
                return ResourceManager.GetString("accounts_accountNo_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        internal static string accountsLov_accountAndDesc_title {
            get {
                return ResourceManager.GetString("accountsLov_accountAndDesc_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Year.
        /// </summary>
        internal static string accountsLov_accountYear_title {
            get {
                return ResourceManager.GetString("accountsLov_accountYear_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Lookup.
        /// </summary>
        internal static string accountsLov_title {
            get {
                return ResourceManager.GetString("accountsLov_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account ID.
        /// </summary>
        internal static string nickAccounts_accountId_label {
            get {
                return ResourceManager.GetString("nickAccounts_accountId_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : ACCOUNT_NICK_NO.
        /// </summary>
        internal static string nickAccounts_accountNickNo_hint {
            get {
                return ResourceManager.GetString("nickAccounts_accountNickNo_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Nick No.
        /// </summary>
        internal static string nickAccounts_accountNickNo_label {
            get {
                return ResourceManager.GetString("nickAccounts_accountNickNo_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : SYS_GEN_FLAG.
        /// </summary>
        internal static string nickAccounts_sysGenFlag_hint {
            get {
                return ResourceManager.GetString("nickAccounts_sysGenFlag_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Generated.
        /// </summary>
        internal static string nickAccounts_sysGenFlag_label {
            get {
                return ResourceManager.GetString("nickAccounts_sysGenFlag_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for : USER_ID.
        /// </summary>
        internal static string nickAccounts_userId_hint {
            get {
                return ResourceManager.GetString("nickAccounts_userId_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        internal static string nickAccounts_userId_label {
            get {
                return ResourceManager.GetString("nickAccounts_userId_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string noRecord_btn1_label {
            get {
                return ResourceManager.GetString("noRecord_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string noRecord_btn2_label {
            get {
                return ResourceManager.GetString("noRecord_btn2_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were no records found - Please choose a mode.
        /// </summary>
        internal static string noRecord_text {
            get {
                return ResourceManager.GetString("noRecord_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a mode.
        /// </summary>
        internal static string noRecord_title {
            get {
                return ResourceManager.GetString("noRecord_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string onErrorCaution_btn1_label {
            get {
                return ResourceManager.GetString("onErrorCaution_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string onErrorStop_btn1_label {
            get {
                return ResourceManager.GetString("onErrorStop_btn1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string onMessage_btn1_label {
            get {
                return ResourceManager.GetString("onMessage_btn1_label", resourceCulture);
            }
        }
    }
}
