
//----------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------------------
using Foundations.Core.AppSupportLib.Runtime.ControlsModel;
using Foundations.Core.AppSupportLib.Runtime.ControlsModel.Containers;
using Foundations.Core.AppSupportLib.Runtime.ControlsModel.Alerts;
using Foundations.Core.AppSupportLib.Runtime.ControlsModel.Lovs;
using Foundations.Flavors.Forms;
using Foundations.Flavors.Forms.Descriptors;
using Foundations.Core.AppSupportLib.Runtime.Task;
using Foundations.Core.AppSupportLib.Composition;
using System.Globalization;

namespace Alio.Forms.Fjgen01a
{	
 
	public partial class Fjgen01aTaskBlocks
	{ 
		public Fjgen01aTaskBlocks(Fjgen01aTask task)
		{
			Journals = new JournalsBlockDescriptor(task);
		}		

		public JournalsBlockDescriptor Journals { get; private set; }


		public class JournalsBlockDescriptor : BlockDescriptorWrapper
        {
            public JournalsBlockDescriptor(AbstractTask task) : base("JOURNALS", task)
            {
                Items = new JournalsItems(this);
            }
            public JournalsItems Items { get; private set; }

            public class JournalsItems
            {
                public JournalsItems(BlockDescriptorWrapper block)
                {
					DupRec = block.FindItem("DUP_REC");
					CheckKey = block.FindItem("CHECK_KEY");
					ClaimNo = block.FindItem("CLAIM_NO");
					ReferenceNo = block.FindItem("REFERENCE_NO");
					ReferenceSeqNo = block.FindItem("REFERENCE_SEQ_NO");
					ReferenceType = block.FindItem("REFERENCE_TYPE");
					BatchYear = block.FindItem("BATCH_YEAR");
					BatchNo = block.FindItem("BATCH_NO");
					AccountPeriod = block.FindItem("ACCOUNT_PERIOD");
					JournalDate = block.FindItem("JOURNAL_DATE");
					JournalType = block.FindItem("JOURNAL_TYPE");
					JournalAmount = block.FindItem("JOURNAL_AMOUNT");
					DebitCreditFlag = block.FindItem("DEBIT_CREDIT_FLAG");
					JournalId = block.FindItem("JOURNAL_ID");
					JournalSeqNo = block.FindItem("JOURNAL_SEQ_NO");
					JournalDescription = block.FindItem("JOURNAL_DESCRIPTION");
					AccountId = block.FindItem("ACCOUNT_ID");
					AccountType = block.FindItem("ACCOUNT_TYPE");
					AccountNo = block.FindItem("ACCOUNT_NO");
					ShowLov = block.FindItem("SHOW_LOV");
					AccountYear = block.FindItem("ACCOUNT_YEAR");
					AccountDesc = block.FindItem("ACCOUNT_DESC");
 
                }

				public ItemDescriptorWrapper DupRec { get; private set; }
				public ItemDescriptorWrapper CheckKey { get; private set; }
				public ItemDescriptorWrapper ClaimNo { get; private set; }
				public ItemDescriptorWrapper ReferenceNo { get; private set; }
				public ItemDescriptorWrapper ReferenceSeqNo { get; private set; }
				public ItemDescriptorWrapper ReferenceType { get; private set; }
				public ItemDescriptorWrapper BatchYear { get; private set; }
				public ItemDescriptorWrapper BatchNo { get; private set; }
				public ItemDescriptorWrapper AccountPeriod { get; private set; }
				public ItemDescriptorWrapper JournalDate { get; private set; }
				public ItemDescriptorWrapper JournalType { get; private set; }
				public ItemDescriptorWrapper JournalAmount { get; private set; }
				public ItemDescriptorWrapper DebitCreditFlag { get; private set; }
				public ItemDescriptorWrapper JournalId { get; private set; }
				public ItemDescriptorWrapper JournalSeqNo { get; private set; }
				public ItemDescriptorWrapper JournalDescription { get; private set; }
				public ItemDescriptorWrapper AccountId { get; private set; }
				public ItemDescriptorWrapper AccountType { get; private set; }
				public ItemDescriptorWrapper AccountNo { get; private set; }
				public ItemDescriptorWrapper ShowLov { get; private set; }
				public ItemDescriptorWrapper AccountYear { get; private set; }
				public ItemDescriptorWrapper AccountDesc { get; private set; }
 
            }
        }
 
	}
  

	public partial class Fjgen01aTaskWindows 
	{ 
		public Fjgen01aTaskWindows(Fjgen01aTask task)
		{
			JournalInqury = new WindowDescriptorWrapper(task.FindWindow("JOURNAL_INQURY"));
		}
		public WindowDescriptor JournalInqury { get; private set; }
	}

	public partial class Fjgen01aTaskCanvases
	{ 
		public Fjgen01aTaskCanvases(Fjgen01aTask task)
		{
			JournalInqury = new CanvasDescriptorWrapper(task.FindCanvas("JOURNAL_INQURY"));
		}
		public CanvasDescriptor JournalInqury { get; private set; }
  
	}
  

	public partial class Fjgen01aTaskAlerts
	{ 
		public Fjgen01aTaskAlerts(Fjgen01aTask task)
		{
			AccountAlert = new AlertDescriptorWrapper(task.FindAlert("ACCOUNT_ALERT"));
			OnMessage = new AlertDescriptorWrapper(task.FindAlert("ON_MESSAGE"));
			OnErrorCaution = new AlertDescriptorWrapper(task.FindAlert("ON_ERROR_CAUTION"));
			OnErrorStop = new AlertDescriptorWrapper(task.FindAlert("ON_ERROR_STOP"));
			NoRecord = new AlertDescriptorWrapper(task.FindAlert("NO_RECORD"));
		}
		public AlertDescriptor AccountAlert { get; private set; }
		public AlertDescriptor OnMessage { get; private set; }
		public AlertDescriptor OnErrorCaution { get; private set; }
		public AlertDescriptor OnErrorStop { get; private set; }
		public AlertDescriptor NoRecord { get; private set; }
  
	}
  

  
}
  